dono = './dados/dono.json'
adicionadas = './dados/db/adicionadas.json'
bins = './dados/db/bins.json'
consul = './dados/db/consul.json'
edits = './editaveis/edits.txt'


pagamentos = './dados/pagamentos.json'
gifts = './dados/gifts.json'

pedidos_de_reembolso = './dados/pedidos/pedidos_de_reembolso.json'
pedidos_mix = './dados/pedidos/pedidos_mix.json'
pedido_de_compra = './dados/pedidos/pedido_de_compra.json'
pedidos_checker = './dados/pedidos/pedidos_checker.json'
pedidos_checker_clientes = './dados/pedidos/pedidos_checker_clientes.json'
reembolso = './dados/reembolso.json'
precos = './dados/preços.json'
quantidade = './dados/quantidade.json'
dados = './dados/dados.json'
config = './dados/config.json'
extrato = './dados/extrato.json'
mix = './dados/mix.json'

logger_cc = './logger_cc.txt'
logger_troca = './logger_troca.txt'
cache = 'cache.txt'
temp_cc = 'ccs_temp.txt'

contas = './editaveis/contas.txt'
start = './editaveis/start.txt'
ranking_texto = './editaveis/ranking_texto.txt'
troca = './editaveis/troca.txt'
vendidas = './editaveis/vendidas.txt'
garantias = './editaveis/garantias.txt'
garantias_consul = './editaveis/garantias_consul.txt'
lara = './editaveis/lara.txt'
texto_pix = './editaveis/texto_pix.txt'
texto_confirmar_pix = './editaveis/texto_confirmar_pix.txt'